### ISSUE TITLE
Task list from Andy/Lucy meeting (1/18)

### ISSUE THREAD

**Issue by lucywowen** [ContextLab/supereeg#51]
- [x] Finish tests (see test issue for point by point)

- [x] Make sure all parameters are defined

- [x] Documentation for new brain plots (plot_data() and plot_locs())

- [x] Only load necessary stats functions in brain and model scripts

- [x] Update tutorials

- [x] Update examples
